package com.pmpmaverick.itto.ui.components;

public interface PMPConstants {
	
	String COLOR_DELIMITER="|";

	String TABLE_COLOUR="TABLE_COLOR";
	String TABLE_SYSTEM_FILTER_COLOUR="TABLE_SYSTEM_FILTER_COLOUR";
	String TABLE_FOREGROUND_COLOUR="TABLE_FOREGROUND_COLOUR";
	String TABLE_DISABLED_FOREGROUND_COLOUR="TABLE_DISABLED_FOREGROUND_COLOUR";
	String TABLE_BACKGROUND_COLOUR="TABLE_BACKGROUND_COLOUR";
	String TABLE_HEADER_FOREGROUND_COLOUR="TABLE_HEADER_FOREGROUND_COLOUR";
	String TABLE_HEADER_BACKGROUND_COLOUR="TABLE_HEADER_BACKGROUND_COLOUR";
	String TABLE_SELECTION_FOREGROUND_COLOUR="TABLE_SELECTION_FOREGROUND_COLOUR";
	String TABLE_SELECTION_BACKGROUND_COLOUR="TABLE_SELECTION_BACKGROUND_COLOUR";
	String TABLE_FONT_NAME="TABLE_FONT_NAME";                         
	String TABLE_FONT_SIZE="TABLE_FONT_SIZE";
	String TABLE_FONT_STYLE="TABLE_FONT_STYLE";
	
	
}
